//
//  MilestoneDurationControls.swift
//  Since
//

import SwiftUI

enum MilestonePreset: CaseIterable {
    case day, week, month, hundredDays, year

    var days: Int {
        switch self {
        case .day: 1
        case .week: 7
        case .month: 30
        case .hundredDays: 100
        case .year: 365
        }
    }

    var label: String {
        switch self {
        case .day: "24 Hours"
        case .week: "1 Week"
        case .month: "1 Month"
        case .hundredDays: "100 Days"
        case .year: "1 Year"
        }
    }
}

/// Row of quick-add chips that set `days` to a common preset value in one tap. Also sets `label`
/// to the preset's name, unless the label has been customized to something that isn't itself a
/// preset name — so tapping a different preset keeps the label in sync with the selected chip,
/// but never clobbers text the user typed by hand.
struct MilestonePresetPicker: View {
    @Binding var days: Int
    @Binding var label: String

    var body: some View {
        ScrollView(.horizontal, showsIndicators: false) {
            HStack(spacing: 8) {
                ForEach(MilestonePreset.allCases, id: \.self) { preset in
                    Button(preset.label) {
                        days = preset.days
                        let trimmedLabel = label.trimmingCharacters(in: .whitespacesAndNewlines)
                        let isAutoGenerated = trimmedLabel.isEmpty
                            || MilestonePreset.allCases.contains { $0.label == trimmedLabel }
                        if isAutoGenerated {
                            label = preset.label
                        }
                    }
                    .buttonStyle(.bordered)
                    .tint(days == preset.days ? .accentColor : .secondary)
                }
            }
        }
        .scrollClipDisabled()
    }
}

/// A `-[value]+` control: the value between the buttons is a `TextField`, so an arbitrary day
/// count can be typed directly instead of only reachable by repeated taps, unlike a stock
/// `Stepper` (whose label sits to the leading edge, not between the +/- controls).
struct DayCountStepper: View {
    @Binding var days: Int

    private let range = 1...3650

    var body: some View {
        HStack(spacing: 0) {
            Button {
                days = max(range.lowerBound, days - 1)
            } label: {
                Image(systemName: "minus")
                    .frame(width: 32, height: 32)
            }
            .disabled(days <= range.lowerBound)
            .accessibilityLabel("Decrease Days")

            TextField("Days", value: $days, format: .number)
                .keyboardType(.numberPad)
                .multilineTextAlignment(.center)
                .frame(minWidth: 44)
                .onChange(of: days) { _, newValue in
                    days = min(max(newValue, range.lowerBound), range.upperBound)
                }

            Button {
                days = min(range.upperBound, days + 1)
            } label: {
                Image(systemName: "plus")
                    .frame(width: 32, height: 32)
            }
            .disabled(days >= range.upperBound)
            .accessibilityLabel("Increase Days")
        }
        .buttonStyle(.bordered)
    }
}
